name: CI

on: push

jobs:
  build:
    name: ğŸ› ï¸ Build and ğŸ§ª Test
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ‘ Checkout
        uses: actions/checkout@v3

      - name: ğŸ’¾ Cache JBR SDK 17.0.9
        id: jbrsdk
        uses: actions/cache@v2
        with:
          path: |
            /opt/jbrsdk-17.0.9
          key: jbrsdk-17.0.9-${{ runner.os }}

      - name: ğŸ“¦ Setup JBR SDK 17.0.9
        if: steps.jbrsdk.outputs.cache-hit != 'true'
        run: |
          set -e
          curl -L https://cache-redirector.jetbrains.com/intellij-jbr/jbrsdk-17.0.9-linux-x64-b1087.7.tar.gz -o jbrsdk-17.0.9.tar.gz
          mkdir /opt/jbrsdk-17.0.9
          tar -xzf jbrsdk-17.0.9.tar.gz -C /opt/jbrsdk-17.0.9 --strip-components=1

      - name: ğŸ”“ Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: ğŸ› ï¸ Build with Gradle
        run: |
          set -e
          export JAVA_HOME=/opt/jbrsdk-17.0.9
          ./gradlew build

      - name: ğŸ§ª Test
        run: |
          set -e
          export JAVA_HOME=/opt/jbrsdk-17.0.9
          ./gradlew test

  publish:
    name: ğŸš€ Publish
    # if: github.ref == 'refs/tags/v*'
    needs: build
    runs-on: { { matrix.os } }
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        include:
          - os: ubuntu-latest
            url: https://cache-redirector.jetbrains.com/intellij-jbr/jbrsdk-17.0.9-linux-x64-b1087.7.tar.gz
            root: /opt/jbrsdk-17.0.9
          - os: macos-latest
            url: https://cache-redirector.jetbrains.com/intellij-jbr/jbrsdk-17.0.9-osx-aarch64-b1087.7.tar.gz
            root: /Library/Java/JavaVirtualMachines/jbrsdk-17.0.9
          - os: windows-latest
            url: https://cache-redirector.jetbrains.com/intellij-jbr/jbrsdk-17.0.9-windows-x64-b1087.7.tar.gz
            root: C:\jbrsdk-17.0.9

    steps:
      - name: ğŸ‘ Checkout
        uses: actions/checkout@v3

      - name: ğŸ’¾ Cache JBR SDK 17.0.9
        id: jbrsdk
        uses: actions/cache@v2
        with:
          path: |
            ${{ matrix.root }}
          key: jbrsdk-17.0.9-${{ runner.os }}

      - name: ğŸ“¦ Setup JBR SDK 17.0.9
        if: steps.jbrsdk.outputs.cache-hit != 'true'
        run: |
          set -e
          curl -L ${{ matrix.url }} -o jbrsdk-17.0.9.tar.gz
          mkdir ${{ matrix.root }}
          tar -xzf jbrsdk-17.0.9.tar.gz -C ${{ matrix.root }} --strip-components=1
