name: CI

on: push

jobs:
  test:
    name: ğŸ§ª Test
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ‘ Checkout
        uses: actions/checkout@v3

      - name: ğŸ’¾ Cache JBR SDK 17.0.9
        id: jbrsdk
        uses: actions/cache@v2
        with:
          path: /opt/jbrsdk-17.0.9
          key: jbrsdk-17.0.9_${{ runner.os }}

      - name: ğŸ“¦ Setup JBR SDK 17.0.9
        if: steps.jbrsdk.outputs.cache-hit != 'true'
        run:
          curl -L https://cache-redirector.jetbrains.com/intellij-jbr/jbrsdk-17.0.9-linux-x64-b1087.7.tar.gz -o jbrsdk-17.0.9.tar.gz
          && mkdir /opt/jbrsdk-17.0.9
          && tar -xzf jbrsdk-17.0.9.tar.gz -C /opt/jbrsdk-17.0.9 --strip-components=1

      - name: ğŸ”“ Grant permission
        run: chmod +x gradlew

      - name: ğŸ› ï¸ Build
        run: export JAVA_HOME=/opt/jbrsdk-17.0.9 && ./gradlew build

      - name: ğŸ§ª Test
        run: export JAVA_HOME=/opt/jbrsdk-17.0.9 && ./gradlew test

  build_windows:
    name: ğŸ› ï¸ Build - Windows
    # if: github.ref == 'refs/tags/v*'
    needs: test
    runs-on: windows-latest

    steps:
      - name: ğŸ‘ Checkout
        uses: actions/checkout@v3

      - name: ğŸ’¾ Cache JBR SDK 17.0.9
        id: jbrsdk-windows
        uses: actions/cache@v2
        with:
          path: C:\jbrsdk-17.0.9
          key: jbrsdk-17.0.9_${{ runner.os }}

      - name: ğŸ“¦ Setup JBR SDK 17.0.9
        if: steps.jbrsdk-windows.outputs.cache-hit != 'true'
        run:
          curl -L https://cache-redirector.jetbrains.com/intellij-jbr/jbrsdk-17.0.9-windows-x64-b1087.7.tar.gz -o jbrsdk-17.0.9.tar.gz
          && mkdir C:\jbrsdk-17.0.9
          && tar -xzvf jbrsdk-17.0.9.tar.gz -C "C:\jbrsdk-17.0.9" --strip-components=1

      - name: ğŸ”“ Grant permission
        run: chmod +x gradlew.bat

      - name: ğŸ› ï¸ Build
        run: |
          $env:JAVA_HOME = "C:\jbrsdk-17.0.9"
          $env:PATH = "$env:JAVA_HOME\bin;$env:PATH"
          ./gradlew.bat build

      - name: ğŸ“¦ Package
        run: |
          $env:JAVA_HOME = "C:\jbrsdk-17.0.9"
          $env:PATH = "$env:JAVA_HOME\bin;$env:PATH"
          ./gradlew.bat jpackage
          dir .\app\build\jpackage

  build_linux:
    name: ğŸ› ï¸ Build - Linux
    # if: github.ref == 'refs/tags/v*'
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ‘ Checkout
        uses: actions/checkout@v3

      - name: ğŸ’¾ Cache JBR SDK 17.0.9
        id: jbrsdk-linux
        uses: actions/cache@v2
        with:
          path: /opt/jbrsdk-17.0.9
          key: jbrsdk-17.0.9_${{ runner.os }}

      - name: ğŸ“¦ Setup JBR SDK 17.0.9
        if: steps.jbrsdk-linux.outputs.cache-hit != 'true'
        run:
          curl -L https://cache-redirector.jetbrains.com/intellij-jbr/jbrsdk-17.0.9-linux-x64-b1087.7.tar.gz -o jbrsdk-17.0.9.tar.gz
          && mkdir /opt/jbrsdk-17.0.9
          && tar -xzf jbrsdk-17.0.9.tar.gz -C /opt/jbrsdk-17.0.9 --strip-components=1

      - name: ğŸ”“ Grant permission
        run: chmod +x gradlew

      - name: ğŸ› ï¸ Build
        run: export JAVA_HOME=/opt/jbrsdk-17.0.9 && ./gradlew build

      - name: ğŸ“¦ Package
        run: export JAVA_HOME=/opt/jbrsdk-17.0.9 && export PATH=$JAVA_HOME/bin:$PATH && echo $JAVA_HOME && javac -version && ./gradlew jpackage --stacktrace && tree ./app/build
