name: CI

on: push

jobs:
  build:
    name: ğŸ› ï¸ Build and ğŸ§ª Test
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ‘ Checkout
        uses: actions/checkout@v3

      - name: ğŸ“¦ Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: ğŸ”“ Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: ğŸ› ï¸ Build with Gradle
        run: ./gradlew build

      - name: ğŸ§ª Test
        run: ./gradlew test
