name: CI

on: [ push, pull_request ]

jobs:
  test:
    name: ğŸ§ª Test
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ‘ Checkout
        uses: actions/checkout@v4

      - name: ğŸ’¾ Cache JBR SDK 17.0.11
        id: jbrsdk
        uses: actions/cache@v4
        with:
          path: /opt/jbrsdk-17.0.11
          key: jbrsdk-17.0.11-${{ runner.os }}

      - name: ğŸ“¦ Setup JBR SDK 17.0.11
        if: steps.jbrsdk.outputs.cache-hit != 'true'
        run: |
          curl -L https://cache-redirector.jetbrains.com/intellij-jbr/jbrsdk-17.0.11-linux-x64-b1312.2.tar.gz -o jbrsdk-17.0.11.tar.gz
          mkdir /opt/jbrsdk-17.0.11
          tar -xzf jbrsdk-17.0.11.tar.gz -C /opt/jbrsdk-17.0.11 --strip-components=1

      - name: â™¨ï¸ Set JAVA_HOME
        run: |
          echo "JAVA_HOME=/opt/jbrsdk-17.0.11" >> $GITHUB_ENV
          echo "PATH=$JAVA_HOME/bin:$PATH" >> $GITHUB_ENV

      - name: ğŸ˜ Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: ğŸ”“ Grant permission
        run: chmod +x gradlew

      - name: ğŸ› ï¸ Build
        run: ./gradlew assemble

      - name: ğŸ§ª Test
        run: ./gradlew test

  package:
    name: ğŸ“¦ Package
    if: startsWith(github.ref, 'refs/tags/v')
    needs: test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-latest, ubuntu-latest, macos-latest ]
        include:
          - os: windows-latest
            url: https://cache-redirector.jetbrains.com/intellij-jbr/jbrsdk-17.0.11-windows-x64-b1312.2.tar.gz
            sdk: C:\jbrsdk-17.0.11
            java_home: C:\jbrsdk-17.0.11
            path: PATH=$env:JAVA_HOME\bin;$env:PATH
            github: $env:GITHUB_ENV
            installer: .\app\build\compose\binaries\main\msi\*.msi

          - os: ubuntu-latest
            url: https://cache-redirector.jetbrains.com/intellij-jbr/jbrsdk-17.0.11-linux-x64-b1312.2.tar.gz
            sdk: /opt/jbrsdk-17.0.11
            java_home: /opt/jbrsdk-17.0.11
            path: PATH=$JAVA_HOME/bin:$PATH
            github: $GITHUB_ENV
            installer: ./app/build/compose/binaries/main/deb/*.deb

          - os: macos-latest
            url: https://cache-redirector.jetbrains.com/intellij-jbr/jbrsdk-17.0.11-osx-x64-b1312.2.tar.gz
            sdk: /Users/runner/jbrsdk-17.0.11
            java_home: /Users/runner/jbrsdk-17.0.11/Contents/Home
            path: PATH=$JAVA_HOME/bin:$PATH
            github: $GITHUB_ENV
            installer: ./app/build/compose/binaries/main/dmg/*.dmg

    steps:
      - name: ğŸ‘ Checkout
        uses: actions/checkout@v4

      - name: ğŸ’¾ Cache JBR SDK 17.0.11
        id: jbrsdk
        uses: actions/cache@v4
        with:
          path: ${{ matrix.sdk }}
          key: jbrsdk-17.0.11-${{ runner.os }}

      - name: ğŸ“¦ Setup JBR SDK 17.0.11
        if: steps.jbrsdk.outputs.cache-hit != 'true'
        run: |
          curl -L ${{ matrix.url }} -o jbrsdk-17.0.11.tar.gz
          mkdir ${{ matrix.sdk }}
          tar -xzvf jbrsdk-17.0.11.tar.gz -C ${{ matrix.sdk }} --strip-components=1

      - name: â™¨ï¸ Set JAVA_HOME
        run: |
          echo "JAVA_HOME=${{ matrix.java_home }}" >> ${{ matrix.github }}
          echo "${{ matrix.path }}" >> ${{ matrix.github }}

      - name: ğŸ”“ Grant permission
        run: chmod +x gradlew

      - name: ğŸ“¦ Package
        run: ./gradlew packageDistributionForCurrentOS

      - name: ğŸ“ Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: installer
          path: ${{ matrix.installer }}
          retention-days: 1

  release:
    name: ğŸš€ Release
    needs: package
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ“¦ Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: installer

      - name: ğŸ—‘ï¸ Delete artifacts
        uses: geekyeggo/delete-artifact@v2
        with:
          name: installer
          failOnError: false

      - name: ğŸš€ Release
        uses: softprops/action-gh-release@v1
        with:
          files: .
