name: CI

on: push

jobs:
  test:
    name: ğŸ§ª Test
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ‘ Checkout
        uses: actions/checkout@v3

      - name: ğŸ’¾ Cache JBR SDK 17.0.9
        id: jbrsdk
        uses: actions/cache@v2
        with:
          path: /opt/jbrsdk-17.0.9
          key: jbrsdk-17.0.9_${{ runner.os }}

      - name: ğŸ“¦ Setup JBR SDK 17.0.9
        if: steps.jbrsdk.outputs.cache-hit != 'true'
        run: |
          curl -L https://cache-redirector.jetbrains.com/intellij-jbr/jbrsdk-17.0.9-linux-x64-b1087.7.tar.gz -o jbrsdk-17.0.9.tar.gz
          mkdir /opt/jbrsdk-17.0.9
          tar -xzf jbrsdk-17.0.9.tar.gz -C /opt/jbrsdk-17.0.9 --strip-components=1

      - name: â™¨ï¸ Set JAVA_HOME
        run: |
          echo "JAVA_HOME=/opt/jbrsdk-17.0.9" >> $GITHUB_ENV
          echo "PATH=$JAVA_HOME/bin:$PATH" >> $GITHUB_ENV

      - name: ğŸ”“ Grant permission
        run: chmod +x gradlew

      - name: ğŸ› ï¸ Build
        run: ./gradlew build

      - name: ğŸ§ª Test
        run: ./gradlew test

  package:
    name: ğŸ“¦ Package
    # if: github.ref == 'refs/tags/v*'
    needs: test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-latest, ubuntu-latest, macos-latest ]
        include:
          - os: windows-latest
            download_url: https://cache-redirector.jetbrains.com/intellij-jbr/jbrsdk-17.0.9-windows-x64-b1087.7.tar.gz
            jbrsdk_path: C:\jbrsdk-17.0.9
            java_home: C:\jbrsdk-17.0.9
            path_env: PATH=$env:JAVA_HOME\bin;$env:PATH
            github_env: $env:GITHUB_ENV
            installer_path: .\app\build\compose\binaries\main\msi\*.msi

          - os: ubuntu-latest
            download_url: https://cache-redirector.jetbrains.com/intellij-jbr/jbrsdk-17.0.9-linux-x64-b1087.7.tar.gz
            jbrsdk_path: /opt/jbrsdk-17.0.9
            java_home: /opt/jbrsdk-17.0.9
            path_env: PATH=$JAVA_HOME/bin:$PATH
            github_env: $GITHUB_ENV
            installer_path: ./app/build/compose/binaries/main/deb/*.deb

          - os: macos-latest
            download_url: https://cache-redirector.jetbrains.com/intellij-jbr/jbrsdk-17.0.9-osx-x64-b1087.7.tar.gz
            jbrsdk_path: /Users/runner/jbrsdk-17.0.9
            java_home: /Users/runner/jbrsdk-17.0.9/Contents/Home
            path_env: PATH=$JAVA_HOME/bin:$PATH
            github_env: $GITHUB_ENV
            installer_path: ./app/build/compose/binaries/main/dmg/*.dmg

    steps:
      - name: ğŸ‘ Checkout
        uses: actions/checkout@v3

      - name: ğŸ’¾ Cache JBR SDK 17.0.9
        id: jbrsdk
        uses: actions/cache@v2
        with:
          path: ${{ matrix.jbrsdk_path }}
          key: jbrsdk-17.0.9_${{ runner.os }}

      - name: ğŸ“¦ Setup JBR SDK 17.0.9
        if: steps.jbrsdk.outputs.cache-hit != 'true'
        run: |
          curl -L ${{ matrix.download_url }} -o jbrsdk-17.0.9.tar.gz
          mkdir ${{ matrix.jbrsdk_path }}
          tar -xzvf jbrsdk-17.0.9.tar.gz -C ${{ matrix.jbrsdk_path }} --strip-components=1

      - name: â™¨ï¸ Set JAVA_HOME
        run: |
          echo "JAVA_HOME=${{ matrix.java_home }}" >> ${{ matrix.github_env }}
          echo "${{ matrix.path_env }}" >> ${{ matrix.github_env }}

      - name: ğŸ”“ Grant permission
        run: chmod +x gradlew

      - name: ğŸ“¦ Package
        run: ./gradlew packageDistributionForCurrentOS

      - name: ğŸ“ Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: installer
          path: ${{ matrix.installer_path }}
          retention-days: 1

  release:
    name: ğŸš€ Release
    needs: package
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ“¦ Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: installer

      - name: ğŸš€ Release
        run: |
          tree .
