name: CI

on: push

jobs:
  test:
    name: ğŸ§ª Test
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ‘ Checkout
        uses: actions/checkout@v3

      - name: ğŸ’¾ Cache JBR SDK 17.0.9
        id: jbrsdk
        uses: actions/cache@v2
        with:
          path: /opt/jbrsdk-17.0.9
          key: jbrsdk-17.0.9_${{ runner.os }}

      - name: ğŸ“¦ Setup JBR SDK 17.0.9
        if: steps.jbrsdk.outputs.cache-hit != 'true'
        run: |
          set -e
          curl -L https://cache-redirector.jetbrains.com/intellij-jbr/jbrsdk-17.0.9-linux-x64-b1087.7.tar.gz -o jbrsdk-17.0.9.tar.gz
          mkdir /opt/jbrsdk-17.0.9
          tar -xzf jbrsdk-17.0.9.tar.gz -C /opt/jbrsdk-17.0.9 --strip-components=1

      - name: ğŸ”“ Grant permission
        run: chmod +x gradlew

      - name: ğŸ› ï¸ Build
        run: ./gradlew build -Dorg.gradle.java.home=/opt/jbrsdk-17.0.9

      - name: ğŸ§ª Test
        run: ./gradlew test -Dorg.gradle.java.home=/opt/jbrsdk-17.0.9

  build_windows:
    name: ğŸ› ï¸ Build - Windows
    # if: github.ref == 'refs/tags/v*'
    needs: test
    runs-on: windows-latest

    steps:
      - name: ğŸ‘ Checkout
        uses: actions/checkout@v3

      - name: ğŸ’¾ Cache JBR SDK 17.0.9
        id: jbrsdk-windows
        uses: actions/cache@v2
        with:
          path: C:\jbrsdk-17.0.9
          key: jbrsdk-17.0.9_${{ runner.os }}

      - name: ğŸ“¦ Setup JBR SDK 17.0.9
        if: steps.jbrsdk-windows.outputs.cache-hit != 'true'
        run: |
          curl -L https://cache-redirector.jetbrains.com/intellij-jbr/jbrsdk-17.0.9-windows-x64-b1087.7.tar.gz -o jbrsdk-17.0.9.tar.gz
          mkdir C:\jbrsdk-17.0.9
          tar -xzvf jbrsdk-17.0.9.tar.gz -C "C:\jbrsdk-17.0.9" --strip-components=1

      - name: ğŸ”“ Grant permission
        run: chmod +x gradlew.bat

      - name: ğŸ“¦ Package
        run: ./gradlew.bat packageDistributionForCurrentOS -Dorg.gradle.java.home=C:\\jbrsdk-17.0.9

  build_linux:
    name: ğŸ› ï¸ Build - Linux
    # if: github.ref == 'refs/tags/v*'
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ‘ Checkout
        uses: actions/checkout@v3

      - name: ğŸ’¾ Cache JBR SDK 17.0.9
        id: jbrsdk-linux
        uses: actions/cache@v2
        with:
          path: /opt/jbrsdk-17.0.9
          key: jbrsdk-17.0.9_${{ runner.os }}

      - name: ğŸ“¦ Setup JBR SDK 17.0.9
        if: steps.jbrsdk-linux.outputs.cache-hit != 'true'
        run: |
          set -e
          curl -L https://cache-redirector.jetbrains.com/intellij-jbr/jbrsdk-17.0.9-linux-x64-b1087.7.tar.gz -o jbrsdk-17.0.9.tar.gz
          mkdir /opt/jbrsdk-17.0.9
          tar -xzf jbrsdk-17.0.9.tar.gz -C /opt/jbrsdk-17.0.9 --strip-components=1

      - name: ğŸ”“ Grant permission
        run: chmod +x gradlew

      - name: ğŸ“¦ Package
        run: ./gradlew packageDistributionForCurrentOS -Dorg.gradle.java.home=/opt/jbrsdk-17.0.9

  build_macos:
    name: ğŸ› ï¸ Build - macOS
    # if: github.ref == 'refs/tags/v*'
    needs: test
    runs-on: macos-latest

    steps:
      - name: ğŸ‘ Checkout
        uses: actions/checkout@v3

      - name: ğŸ’¾ Cache JBR SDK 17.0.9
        id: jbrsdk-macos
        uses: actions/cache@v2
        with:
          path: /Users/runner/jbrsdk-17.0.9
          key: jbrsdk-17.0.9_${{ runner.os }}

      - name: ğŸ“¦ Setup JBR SDK 17.0.9
        if: steps.jbrsdk-macos.outputs.cache-hit != 'true'
        run:
          curl -L https://cache-redirector.jetbrains.com/intellij-jbr/jbrsdk-17.0.9-osx-x64-b1087.7.tar.gz -o jbrsdk-17.0.9.tar.gz
          && mkdir /Users/runner/jbrsdk-17.0.9
          && tar -xzf jbrsdk-17.0.9.tar.gz -C /Users/runner/jbrsdk-17.0.9 --strip-components=1

      - name: ğŸ”“ Grant permission
        run: chmod +x gradlew

      - name: ğŸ“¦ Package
        run: ./gradlew packageDistributionForCurrentOS -Dorg.gradle.java.home=/Users/runner/jbrsdk-17.0.9/Contents/Home
