name: CI

on: push

jobs:
  build:
    name: ğŸ› ï¸ Build and ğŸ§ª Test
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ‘ Checkout
        uses: actions/checkout@v3

      - name: ğŸ“¦ Setup Jetbrains Runtime 17
        uses: actions/cache@v2
        with:
          path: |
            /opt/jbrsdk-17.0.9
          key: jbrsdk-17.0.9-${{ runner.os }}
        run: |
          set -e
          curl -L https://cache-redirector.jetbrains.com/intellij-jbr/jbrsdk-17.0.9-linux-x64-b1087.7.tar.gz -o jbrsdk-17.0.9.tar.gz
          mkdir /opt/jbrsdk-17.0.9
          tar -xzf jbrsdk-17.0.9.tar.gz -C /opt/jbrsdk-17.0.9 --strip-components=1

      - name: ğŸ”“ Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: ğŸ› ï¸ Build with Gradle
        run: |
          set -e
          export JAVA_HOME=/opt/jbrsdk-17.0.9
          ./gradlew build

      - name: ğŸ§ª Test
        run: |
          set -e
          export JAVA_HOME=/opt/jbrsdk-17.0.9
          ./gradlew test
